language: python
cache: pip
install:
  - python3 -m pip install cffi pytest flake8 networkx numpy>=1.17.0 matplotlib
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then python3 -m pip install black; fi
  - python3 -m pip install .
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then python3 -m black mip --line-length=89 --check; fi
  - python3 -m flake8 mip --select=F401 --exclude=__init__.py # Look for unused imports
  - python3 -m pytest test --verbose --color=yes --doctest-modules
  - python3 -m pytest mip --verbose --color=yes --doctest-modules --ignore="mip/gurobi.py"
jobs:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      python: 3.6
    - name: "Python 3.7 on Linux"
      os: linux
      python: 3.7
    - name: "Python 3.8 on Linux"
      os: linux
      python: 3.8
    - name: "Python 3.9 on Linux"
      os: linux
      python: 3.9
    - name: "Python 3.7 on macOS 10.14.6"
      os: osx
      osx_image: xcode11.4
      env: PYTHON=37
      language: shell # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8 on Windows"
      os: windows # Windows 10.0.17134 N/A Build 17134
      language: shell # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.3
        - python -m pip install --upgrade pip
        - cp /c/Python38/python.exe /c/Python38/python3.exe
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
