language: python
os:
    - linux
    - osx
python:
    - "3.5"
    - "3.6"
    - "3.7"
cache: pip
install:
    - pip install cffi pytest flake8 networkx black
    - pip install .
script:
    - black mip --line-length=79
    - flake8 mip --select=F401 --exclude=__init__.py # Look for unused imports
    - pytest test --verbose --color=yes --doctest-modules
    - pytest mip --verbose --color=yes --doctest-modules --ignore="mip/gurobi.py"
    - # Ensure that the examples used in the docs run (TODO: Generalize this)
    - python examples/knapsack.py
    - python examples/tsp-compact.py
    - python examples/queens.py
    - python examples/bmcp.py
    - python examples/rcpsp.py
    - python examples/jssp.py
    - python examples/cutting_planes.py
jobs:
  allow_failures:
    - os: osx
